---
date: 2017-04-10
section_name: 산업
is_front_page: false
:ad_type: no_ad
page_columns: 6
grid_size:
- 159.21666666666667
- 96.94466666666668
width: 1116.85
height: 1539.21
left_margin: 42.52
top_margin: 42.52
right_margin: 42.52
bottom_margin: 42.52
gutter: 12.75
divider_info:
- 3
- 25.51
story_frames:
- - 0
  - 0
  - 3
  - 7
- - 3
  - 0
  - 3
  - 4
- - 3
  - 4
  - 3
  - 3
- - 0
  - 7
  - 2
  - 3
- - 2
  - 7
  - 2
  - 4
- - 4
  - 7
  - 2
  - 4
- - 0
  - 10
  - 2
  - 3
- - 0
  - 13
  - 2
  - 2
- - 2
  - 11
  - 1
  - 4
- - 3
  - 11
  - 3
  - 2
- - 3
  - 13
  - 3
  - 2
