issue_plan = [
  {:page_number=>1},
  {:page_number=>2, :profile=>"7x15_7"},
  {:page_number=>3, :profile=>"7x15_9단21_4"},
  {:page_number=>4, :profile=>"7x15_9", :column=>7, :row=>15, :story_count=>9, :color_page=>false},
  {:page_number=>5, :profile=>"7x15_8", :column=>7, :row=>15, :story_count=>8, :color_page=>false},
  {:page_number=>6, :profile=>"6x15_5", :column=>6, :row=>15, :story_count=>5, :color_page=>false},
  {:page_number=>7, :profile=>"7x15_7", :column=>7, :row=>15, :story_count=>7, :color_page=>false},
  {:page_number=>8, :profile=>"7x15_5단통_4", :column=>7, :row=>15, :ad_type=>"5단통", :story_count=>4, :color_page=>false},
  {:page_number=>9, :profile=>"7x15_8", :column=>7, :row=>15, :story_count=>8, :color_page=>false},
  {:page_number=>10, :profile=>"7x15_8", :column=>7, :row=>15, :story_count=>8, :color_page=>false},
  {:page_number=>11, :profile=>"7x15_8", :column=>7, :row=>15, :story_count=>8, :color_page=>false},
  {:page_number=>12, :profile=>"7x15_6", :column=>7, :row=>15, :story_count=>6, :color_page=>false},
  {:page_number=>13, :profile=>"7x15_6", :column=>7, :row=>15, :story_count=>6, :color_page=>false},
  {:page_number=>14, :profile=>"6x15_5단통_6", :column=>6, :row=>15, :ad_type=>"5단통", :story_count=>6, :color_page=>true},
  {:page_number=>15, :profile=>"7x15_5단통_7", :column=>7, :row=>15, :ad_type=>"5단통", :story_count=>7, :color_page=>true},
  {:page_number=>16, :profile=>"6x15_12", :column=>6, :row=>15, :story_count=>12, :color_page=>true},
  {:page_number=>17, :profile=>"7x15_5단통_5", :column=>7, :row=>15, :ad_type=>"5단통", :story_count=>5, :color_page=>true},
  {:page_number=>18, :profile=>"7x15_8", :column=>7, :row=>15, :story_count=>8, :color_page=>true},
  {:page_number=>19, :profile=>"6x15_6", :column=>6, :row=>15, :story_count=>6, :color_page=>false},
  {:page_number=>20, :profile=>"7x15_8", :column=>7, :row=>15, :story_count=>8, :color_page=>true},
  {:page_number=>21, :profile=>"7x15_4", :column=>7, :row=>15, :story_count=>4, :color_page=>true},
  {:page_number=>22, :profile=>"7x15_4", :column=>7, :row=>15, :story_count=>4, :color_page=>true},
  {:page_number=>23, :profile=>"7x15_5단통_4", :column=>7, :row=>15, :ad_type=>"5단통", :story_count=>4, :color_page=>true},
  {:page_number=>24, :profile=>"7x15_5단통_4", :column=>7, :row=>15, :ad_type=>"5단통", :story_count=>4, :color_page=>true},

]
