issue_plan = [
  {page_number: 1, column:7, ad_type:'5단통', story_count:3},
  {page_number: 2, column:7, ad_type:'5단통', story_count:5},
  {page_number: 3, column:7, ad_type:'9단21', story_count:4},
  {page_number: 4, column:7, ad_type:'', story_count:9},
  {page_number: 5, column:6, ad_type:'', story_count:5},
  {page_number: 6, column:6, ad_type:'', story_count:5},
  {page_number: 7, column:6, ad_type:'', story_count:5},
  {page_number: 8, column:7, ad_type:'5단통', story_count:6},
  {page_number: 9, column:7, ad_type:'5단통', story_count:4},
  {page_number: 10, column:7, ad_type:'', story_count:8},
  {page_number: 11, column:7, ad_type:'', story_count:6},
  {page_number: 12, column:7, ad_type:'', story_count:8},
  {page_number: 13, column:7, ad_type:'', story_count:8},
  {page_number: 14, column:7, ad_type:'5단통', story_count:6},
  {page_number: 15, column:7, ad_type:'9단21', story_count:7},
  {page_number: 16, column:6, ad_type:'', story_count:12},
  {page_number: 17, column:6, ad_type:'', story_count:6},
  {page_number: 18, column:7, ad_type:'', story_count:9},
  {page_number: 19, column:7, ad_type:'', story_count:7},
  {page_number: 20, column:6, ad_type:'', story_count:7},
  {page_number: 21, column:7, ad_type:'', story_count:9},
  {page_number: 22, column:6, ad_type:'5단통', story_count:3},
  {page_number: 23, column:6, ad_type:'5단통', story_count:3},
  {page_number: 24, column:7, ad_type:'5단통', story_count:4},

]