
styles =[
  {:name=>"본문명조", :english=>"body", :font_family=>"윤신문명조", :font=>"YDVYSinStd", :font_size=>"9.6", :text_color=>"", :alignment=>"justified", :tracking=>"-0.5", :space_width=>"5.0", :scale=>"100.0", :text_line_spacing=>nil, :space_before_in_lines=>nil, :text_height_in_lines=>nil, :space_after_in_lines=>nil, :custom_font=>nil, :publication_id=>"1"},
  {:name=>"본문고딕", :english=>"body_gothic", :font_family=>"윤고딕120", :font=>"YDVYGOStd12", :font_size=>"9.4", :text_color=>"", :alignment=>"justified", :tracking=>"-0.5", :space_width=>"5.0", :scale=>"100.0", :text_line_spacing=>nil, :space_before_in_lines=>nil, :text_height_in_lines=>nil, :space_after_in_lines=>nil, :custom_font=>nil, :publication_id=>"1"},
  {:name=>"본문중제", :english=>"running_head", :font_family=>"윤고딕130", :font=>"YDVYGOStd13", :font_size=>"9.6", :text_color=>"", :alignment=>"left", :tracking=>"-0.5", :space_width=>"5.0", :scale=>"100.0", :text_line_spacing=>nil, :space_before_in_lines=>nil, :text_height_in_lines=>nil, :space_after_in_lines=>nil, :custom_font=>nil, :publication_id=>"1"},
  {:name=>"발문", :english=>"quote", :font_family=>"윤명조130", :font=>"YDVYMjOStd13", :font_size=>"12.0", :text_color=>"", :alignment=>"center", :tracking=>"-0.5", :space_width=>"6.0", :scale=>"100.0", :text_line_spacing=>nil, :space_before_in_lines=>nil, :text_height_in_lines=>nil, :space_after_in_lines=>nil, :custom_font=>nil, :publication_id=>"1"},
  {:name=>"관련기사", :english=>"related story", :font_family=>"윤고딕120", :font=>"YDVYGOStd12", :font_size=>"9.4", :text_color=>"", :alignment=>"right", :tracking=>"-0.5", :space_width=>"5.0", :scale=>"100.0", :text_line_spacing=>nil, :space_before_in_lines=>nil, :text_height_in_lines=>nil, :space_after_in_lines=>nil, :custom_font=>nil, :publication_id=>"1"},
  {:name=>"사진제목", :english=>"caption_title", :font_family=>"윤고딕140", :font=>"YDVYGOStd14", :font_size=>"8.0", :text_color=>"", :alignment=>"left", :tracking=>"-0.5", :space_width=>"4.0", :scale=>"100.0", :text_line_spacing=>nil, :space_before_in_lines=>nil, :text_height_in_lines=>nil, :space_after_in_lines=>nil, :custom_font=>nil, :publication_id=>"1"},
  {:name=>"사진설명", :english=>"caption", :font_family=>"윤고딕120", :font=>"YDVYGOStd12", :font_size=>"8.0", :text_color=>"", :alignment=>"left", :tracking=>"-0.5", :space_width=>"4.0", :scale=>"100.0", :text_line_spacing=>nil, :space_before_in_lines=>nil, :text_height_in_lines=>nil, :space_after_in_lines=>nil, :custom_font=>nil, :publication_id=>"1"},
  {:name=>"사진출처", :english=>"source", :font_family=>"윤고딕120", :font=>"YDVYGOStd12", :font_size=>"7.0", :text_color=>"", :alignment=>"right", :tracking=>"-0.5", :space_width=>"4.0", :scale=>"80.0", :text_line_spacing=>nil, :space_before_in_lines=>nil, :text_height_in_lines=>nil, :space_after_in_lines=>nil, :custom_font=>nil, :publication_id=>"1"},
  {:name=>"기자명", :english=>"reporter", :font_family=>"윤고딕120", :font=>"YDVYGOStd12", :font_size=>"8.0", :text_color=>"", :alignment=>"right", :tracking=>"-0.5", :space_width=>"5.0", :scale=>"100.0", :text_line_spacing=>nil, :space_before_in_lines=>nil, :text_height_in_lines=>nil, :space_after_in_lines=>nil, :custom_font=>nil, :publication_id=>"1"},
  {:name=>"제목_메인", :english=>"title_top", :font_family=>"윤명조140", :font=>"YDVYMjOStd14", :font_size=>"42.0", :text_color=>"", :alignment=>"left", :tracking=>"-0.5", :space_width=>"21.0", :scale=>"100.0", :text_line_spacing=>nil, :space_before_in_lines=>"2", :text_height_in_lines=>"4", :space_after_in_lines=>"2", :custom_font=>nil, :publication_id=>"1"},
  {:name=>"제목_4-5단", :english=>"title_4_5", :font_family=>"윤명조140", :font=>"YDVYMjOStd14", :font_size=>"32.0", :text_color=>"", :alignment=>"left", :tracking=>"-0.5", :space_width=>"18.0", :scale=>"100.0", :text_line_spacing=>nil, :space_before_in_lines=>"2", :text_height_in_lines=>"4", :space_after_in_lines=>"2", :custom_font=>nil, :publication_id=>"1"},
  {:name=>"제목_3단", :english=>"title_3", :font_family=>"윤명조140", :font=>"YDVYMjOStd14", :font_size=>"26.0", :text_color=>"", :alignment=>"left", :tracking=>"-0.5", :space_width=>"13.0", :scale=>"100.0", :text_line_spacing=>nil, :space_before_in_lines=>"2", :text_height_in_lines=>"4", :space_after_in_lines=>"2", :custom_font=>nil, :publication_id=>"1"},
  {:name=>"제목_2단", :english=>"title_2", :font_family=>"윤명조140", :font=>"YDVYMjOStd14", :font_size=>"22.0", :text_color=>"", :alignment=>"left", :tracking=>"-0.5", :space_width=>"11.0", :scale=>"100.0", :text_line_spacing=>nil, :space_before_in_lines=>"1", :text_height_in_lines=>"3", :space_after_in_lines=>"2", :custom_font=>nil, :publication_id=>"1"},
  {:name=>"제목_1단", :english=>"title_1", :font_family=>"윤명조140", :font=>"YDVYMjOStd14", :font_size=>"15.0", :text_color=>"", :alignment=>"left", :tracking=>"-0.5", :space_width=>"7.0", :scale=>"100.0", :text_line_spacing=>nil, :space_before_in_lines=>"1", :text_height_in_lines=>"3", :space_after_in_lines=>"2", :custom_font=>nil, :publication_id=>"1"},
  {:name=>"부제_메인", :english=>"subtitle_main", :font_family=>"윤명조140", :font=>"YDVYMjOStd14", :font_size=>"18.0", :text_color=>"", :alignment=>"left", :tracking=>"-0.5", :space_width=>"9.0", :scale=>"100.0", :text_line_spacing=>"6.0", :space_before_in_lines=>"1", :text_height_in_lines=>"2", :space_after_in_lines=>"1", :custom_font=>nil, :publication_id=>"1"},
  {:name=>"부제_14", :english=>"subtitle_14", :font_family=>"윤명조140", :font=>"YDVYMjOStd14", :font_size=>"14.0", :text_color=>"", :alignment=>"left", :tracking=>"-0.5", :space_width=>"7.0", :scale=>"100.0", :text_line_spacing=>"7.0", :space_before_in_lines=>"1", :text_height_in_lines=>"2", :space_after_in_lines=>"1", :custom_font=>nil, :publication_id=>"1"},
  {:name=>"부제_12", :english=>"subtitle_12", :font_family=>"윤명조140", :font=>"YDVYMjOStd14", :font_size=>"12.0", :text_color=>"", :alignment=>"left", :tracking=>"-0.5", :space_width=>"6.0", :scale=>"100.0", :text_line_spacing=>nil, :space_before_in_lines=>nil, :text_height_in_lines=>nil, :space_after_in_lines=>nil, :custom_font=>nil, :publication_id=>"1"},
  {:name=>"뉴스라인_제목", :english=>"news line_title", :font_family=>"윤고딕120", :font=>"YDVYGOStd12", :font_size=>"13.0", :text_color=>"", :alignment=>"left", :tracking=>"-0.5", :space_width=>"6.0", :scale=>nil, :text_line_spacing=>nil, :space_before_in_lines=>nil, :text_height_in_lines=>nil, :space_after_in_lines=>nil, :custom_font=>nil, :publication_id=>"1"},
  {:name=>"애드_브랜드명", :english=>"brand_naming", :font_family=>"윤고딕130", :font=>"YDVYMjOStd13", :font_size=>"13.0", :text_color=>"", :alignment=>"center", :tracking=>"-0.5", :space_width=>"6.0", :scale=>nil, :text_line_spacing=>nil, :space_before_in_lines=>nil, :text_height_in_lines=>nil, :space_after_in_lines=>nil, :custom_font=>nil, :publication_id=>"1"},
  {:name=>"문패_18", :english=>"subject_head", :font_family=>"윤고딕140", :font=>"YDVYGOStd14", :font_size=>"18.0", :text_color=>"CMYK=100,60,0,0", :alignment=>"left", :tracking=>"-0.5", :space_width=>"9.0", :scale=>nil, :text_line_spacing=>nil, :space_before_in_lines=>nil, :text_height_in_lines=>nil, :space_after_in_lines=>nil, :custom_font=>nil, :publication_id=>"1"},
  {:name=>"문패_14", :english=>"subject_head", :font_family=>"윤고딕140", :font=>"YDVYGOStd14", :font_size=>"14.0", :text_color=>"", :alignment=>"left", :tracking=>"-0.5", :space_width=>"7.0", :scale=>"100.0", :text_line_spacing=>nil, :space_before_in_lines=>nil, :text_height_in_lines=>nil, :space_after_in_lines=>nil, :custom_font=>nil, :publication_id=>"1"},
  {:name=>"문패_12", :english=>"subject_head", :font_family=>"윤고딕140", :font=>"YDVYGOStd14", :font_size=>"12.0", :text_color=>"", :alignment=>"left", :tracking=>"-0.5", :space_width=>"6.0", :scale=>nil, :text_line_spacing=>nil, :space_before_in_lines=>nil, :text_height_in_lines=>nil, :space_after_in_lines=>nil, :custom_font=>nil, :publication_id=>"1"},
  {:name=>"편집자주", :english=>"editor_note", :font_family=>"윤고딕130", :font=>"YDVYGOStd13", :font_size=>"8.8", :text_color=>"CMYK=0,0,0,80", :alignment=>"left", :tracking=>"-0.5", :space_width=>"5.0", :scale=>nil, :text_line_spacing=>nil, :space_before_in_lines=>nil, :text_height_in_lines=>nil, :space_after_in_lines=>nil, :custom_font=>nil, :publication_id=>"1"}
]

 new_style =styles.map do |style_hash|
  Hash[style_hash.map{ |k, v| [k, v.to_f] }]
end

puts "+++++ "
puts new_style
