---
date: 2017-04-10
section_name: 1면
is_front_page: true
page_heading_margin_in_lines: 8
:ad_type: 5단통
page_columns: 7
grid_size:
- 147.40142857142857
- 96.94466666666668
lines_per_grid: 7
width: 1116.85
height: 1539.21
left_margin: 42.52
top_margin: 42.52
right_margin: 42.52
bottom_margin: 42.52
gutter: 12.75
draw_divider: 
story_frames:
- - 0
  - 1
  - 5
  - 3
- - 0
  - 4
  - 5
  - 3
- - 5
  - 1
  - 2
  - 5
- - 0
  - 7
  - 3
  - 3
- - 3
  - 7
  - 2
  - 3
- - 5
  - 6
  - 2
  - 4
- - 0
  - 10
  - 7
  - 5
  - 광고_5단통
article_line_thickness: 0.3
