---
date: 2017-04-10
section_name: 금융
is_front_page: false
:ad_type: no_ad
page_columns: 7
grid_size:
- 137.40142857142857
- 96.94466666666668
width: 1116.85
height: 1539.21
left_margin: 42.52
top_margin: 42.52
right_margin: 42.52
bottom_margin: 42.52
gutter: 10.0
divider_info:
- 4
- 20.0
story_frames:
- - 0
  - 0
  - 7
  - 2
- - 0
  - 2
  - 4
  - 6
- - 4
  - 2
  - 3
  - 6
- - 0
  - 8
  - 4
  - 3
- - 4
  - 8
  - 3
  - 3
- - 0
  - 11
  - 2
  - 4
- - 2
  - 11
  - 2
  - 4
- - 4
  - 11
  - 3
  - 4
